server:
  port: 9303

spring:
  datasource:
    name: oauth2_v1
    url: jdbc:mysql://127.0.0.1:3306/oauth2_v1?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    # 使用druid数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      maxActive: 20
      initialSize: 5
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      removeAbandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true


  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        #驼峰转下划线命名
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        #无修改命名
        #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    #指定方言,使用innodb引擎,支持失误,默认的MyISAM不支持失误
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
